# Generated by Django 5.0.3 on 2024-03-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RootData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name="label",
            old_name="label",
            new_name="label_pro",
        ),
    ]
