# Generated by Django 5.0.3 on 2024-03-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UI", "0002_rootdata_rename_label_label_label_pro"),
    ]

    operations = [
        migrations.AddField(
            model_name="rootdata",
            name="text",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name="rootdata",
            name="label",
            field=models.CharField(default=None, max_length=64),
        ),
    ]
