# Generated by Django 5.0.3 on 2024-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UI", "0003_rootdata_text_alter_rootdata_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootdata",
            name="label",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="rootdata",
            name="text",
            field=models.CharField(max_length=64),
        ),
    ]
